apiVersion: v1 
kind: PersistentVolume 
metadata: 
   name: mynfspv 
spec: 
   accessModes: 
     - ReadWriteMany 
   storageClassName: myclass
   capacity: 
     storage: 100Mi 
   nfs:
     server: 192.168.56.1
     path: "/srv/exports"
