apiVersion: v1 
kind: PersistentVolume 
metadata: 
   name: pv-mailhogoo
spec: 
   accessModes: 
     - ReadWriteOnce 
   storageClassName: manual 
   capacity: 
     storage: 10Mi 
   hostPath: 
     path: /tmp/pv-mailhogoo
