apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
   name: pvc2-mailhog 
spec: 
   accessModes: 
     - ReadWriteOnce 
   storageClassName: manual 
   resources: 
     requests: 
       storage: 10Mi 
   volumeName: pv-mailhog

