apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
   name: mynfspvc
spec: 
   accessModes: 
     - ReadWriteMany  
   storageClassName: myclass
   resources: 
     requests: 
       storage: 9Mi 

